language: ruby
addons:
  chrome: beta
# branches:
#   if: type = pull_request
#   only: 
#     - main
before_install:
  — gem install bundler:2.2.7
  — cd BookManager
  — bundle exec rails server
  — google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
rvm: 2.5.7
script:
  — cd BookManager — jobs=3 — retry=3
  — rails test test/selenium_tests
  # — bundle install
  # — bundle exec rake db:create
  # — bundle exec rake db:migrate
  # — bundle exec rspec
##
# deploy:
#   provider: heroku
#   api_key: 
#     secure: "4363ed76-1093-421e-a957-1ce7d575732a"
#   app: bookmanager
#   on: main