language: ruby
addons:
  chrome: beta
# branches:
#   if: type = pull_request
#   only: 
#     - main
before_install:
  — cd BookManager
  — gem install bundler:2.2.7
  — rails server
  — "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"
rvm: 2.5.7
script:
  — cd BookManager — jobs=3 — retry=3
  # — bundle install
  # — bundle exec rake db:create
  # — bundle exec rake db:migrate
  # — bundle exec rspec
  — rails test test/selenium_tests
##
# deploy:
#   provider: heroku
#   api_key: 
#     secure: "4363ed76-1093-421e-a957-1ce7d575732a"
#   app: bookmanager
#   on: main